#!/bin/bash
 
set -e 

read -p "Empty ./plots/? (y/N): " answer
if [[ "$answer" =~ ^[Yy]$ ]]; then
    echo -e "Emptying ./plots/\n"
    rm -rf ./plots/*
    
else
    echo -e "./plots/ not emptied\n"
fi

echo -e "Creating ./plots/ and ./plots/frames/\n"
mkdir -p ./plots/frames/

read -p "Run simulation? (y/N): " answer
if [[ "$answer" =~ ^[Yy]$ ]]; then
    echo -e "Starting Simulation\n"
    python3 ./main.py

    ffplay -framerate 5 -i ./plots/frames/%d.png
    
else
    echo -e "Nothing was done\n"
fi

